// src/components/CreateShortcutDialog.vue
<script setup lang="ts">
import CreateShortcutForm from "@/components/CreateShortcutForm.vue";
import Button from "@/components/ui/button/Button.vue";
import Dialog from "@/components/ui/dialog/Dialog.vue";
import DialogContent from "@/components/ui/dialog/DialogContent.vue";
import DialogDescription from "@/components/ui/dialog/DialogDescription.vue";
import DialogHeader from "@/components/ui/dialog/DialogHeader.vue";
import DialogTitle from "@/components/ui/dialog/DialogTitle.vue";
import DialogTrigger from "@/components/ui/dialog/DialogTrigger.vue";
import Field from "@/components/ui/field/Field.vue";
import Spinner from "@/components/ui/spinner/Spinner.vue";
import { shortcutItemClassName } from "@/lib/constants";
import { t } from "@/lib/i18n";
import { storage } from "@/lib/storage";
import { cn, createShortcut, CreateShortcutInput } from "@/lib/utils";
import { PlusIcon } from "@lucide/vue";
import { ref } from "vue";

const isDialogOpen = ref(false);

const formData = ref<CreateShortcutInput>({
  url: "",
  name: "",
  accentColor: "",
  mutedColor: "",
});

const isPending = ref(false);

const onFormSubmit = async () => {
  isPending.value = true;
  isDialogOpen.value = false;

  const newShortcut = await createShortcut(formData.value, {
    faviconErrorMessage: t("shortcut.faviconError"),
  });

  if (!newShortcut) {
    return;
  }

  storage.shortcuts = [...storage.shortcuts, newShortcut];

  formData.value = { url: "", name: "", accentColor: "", mutedColor: "" };

  isPending.value = false;
};
</script>

<template>
  <div
    v-if="isPending"
    :class="cn([shortcutItemClassName, 'border border-accent'])"
  >
    <Spinner />
  </div>
  <Dialog v-else v-model="isDialogOpen">
    <DialogTrigger
      type="button"
      :class="
        cn([
          shortcutItemClassName,
          'border border-dashed size-full border-accent text-accent bg-accent/2 hover:bg-accent/10 transition-all duration-300 animate-in fade-in',
          {
            'opacity-0 hover:opacity-100':
              storage.settings.transparentAddShortcut,
          },
        ])
      "
    >
      <PlusIcon />
    </DialogTrigger>
    <DialogContent>
      <DialogHeader>
        <DialogTitle>{{ t("shortcut.createTitle") }}</DialogTitle>
        <DialogDescription></DialogDescription>
      </DialogHeader>
      <form
        @submit="
          async (e) => {
            e.preventDefault();
            await onFormSubmit();
          }
        "
      >
        <div class="grid grid-cols-1 gap-4">
          <CreateShortcutForm v-model="formData" hasOptional />
          <Field>
            <Button type="submit">{{ t("common.create") }}</Button>
          </Field>
        </div>
      </form>
    </DialogContent>
  </Dialog>
</template>

// src/newtab/components/create-shortcut-dialog.tsx
import { PlusIcon } from "lucide-react";
import { useState } from "react";
import { useStorage } from "@/components/providers/storage-provider";
import { Button } from "@/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from "@/components/ui/dialog";
import { Field } from "@/components/ui/field";
import { Spinner } from "@/components/ui/spinner";
import { useI18n } from "@/lib/i18n";
import { type CreateShortcutInput, cn, createShortcut } from "@/lib/utils";
import CreateShortcutForm from "@/newtab/components/create-shortcut-form";
import { shortcutItemClassName } from "@/newtab/components/shortcut-item";

const CreateShortcutDialog = () => {
	const { setShortcuts, storage } = useStorage();
	const { t } = useI18n();

	const [open, setOpen] = useState(false);

	const [formData, setFormData] = useState<CreateShortcutInput>({
		url: "",
		name: "",
		accentColor: undefined,
		mutedColor: undefined,
	});

	const [isPending, setIsPending] = useState(false);

	const onFormSubmit = async () => {
		setIsPending(true);
		setOpen(false);

		const newShortcut = await createShortcut(formData, {
			faviconErrorMessage: t("shortcut.faviconError"),
		});
		setShortcuts([...storage.shortcuts, newShortcut]);

		setFormData({ url: "", name: "" });
		setIsPending(false);
	};

	if (isPending)
		return (
			<div className={cn([shortcutItemClassName, "border border-accent"])}>
				<Spinner />
			</div>
		);

	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogTrigger
				type="button"
				className={cn([
					shortcutItemClassName,
					"border border-dashed size-full border-accent text-accent bg-accent/2 hover:bg-accent/10 transition-all duration-300 animate-in fade-in",
					{
						"opacity-0 hover:opacity-100 ":
							storage.settings.transparentAddShortcut,
					},
				])}
			>
				<PlusIcon />
			</DialogTrigger>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>{t("shortcut.createTitle")}</DialogTitle>
				</DialogHeader>
				<form
					onSubmit={async (e) => {
						e.preventDefault();
						await onFormSubmit();
					}}
				>
					<div className="grid grid-cols-1 gap-4">
						<CreateShortcutForm
							onFormDataChange={setFormData}
							formData={formData}
						/>
						<Field>
							<Button type="submit">{t("common.create")}</Button>
						</Field>
					</div>
				</form>
			</DialogContent>
		</Dialog>
	);
};

export default CreateShortcutDialog;
