// src/components/CreateShortcutForm.vue
<script setup lang="ts">
import Field from "@/components/ui/field/Field.vue";
import FieldDescription from "@/components/ui/field/FieldDescription.vue";
import FieldLabel from "@/components/ui/field/FieldLabel.vue";
import Input from "@/components/ui/input/Input.vue";
import { t } from "@/lib/i18n";
import { CreateShortcutInput } from "@/lib/utils";


const formData = defineModel<CreateShortcutInput>({
  default: () => ({
    url: "",
    accentColor: "#000",
    mutedColor: "#000",
    name: "",
  }),
});

const { hasOptional } = defineProps<{
  hasOptional?: boolean;
}>();
</script>

<template>
  <div class="grid grid-cols-1 gap-4">
    <Field>
      <FieldLabel for="url">{{ t("shortcut.url") }}</FieldLabel>
      <Input
        id="url"
        name="url"
        autoComplete="off"
        required
        placeholder="https://example.com"
        type="url"
        v-model="formData.url"
      />
    </Field>
    <Field>
      <FieldLabel for="name">
        {{ t("shortcut.name") }}
        <template v-if="hasOptional">
          {{ `(${t("common.optional")})` }}
        </template>
      </FieldLabel>
      <Input
        id="name"
        name="name"
        autoComplete="off"
        placeholder="Example.com"
        v-model="formData.name"
      />
      <FieldDescription v-if="hasOptional">
        {{ t("shortcut.nameDescription") }}
      </FieldDescription>
    </Field>
    <Field>
      <FieldLabel htmlFor="accentColor">
        {{ t("shortcut.bgColor") }}
        <template v-if="hasOptional">
          {{ `(${t("common.optional")})` }}
        </template>
      </FieldLabel>
      <Input id="accentColor" type="color" v-model="formData.accentColor" />
      <FieldDescription v-if="hasOptional">{{
        t("shortcut.colorDescription")
      }}</FieldDescription>
    </Field>

    <Field>
      <FieldLabel htmlFor="mutedColor">
        {{ t("shortcut.mutedColor") }}
        <template v-if="hasOptional">
          {{ `(${t("common.optional")})` }}
        </template>
      </FieldLabel>
      <Input id="mutedColor" type="color" v-model="formData.mutedColor" />
      <FieldDescription v-if="hasOptional">
        {{ t("shortcut.colorDescription") }}
      </FieldDescription>
    </Field>
  </div>
</template>

// src/newtab/components/create-shortcut-form.tsx
import { useDebouncedCallback } from "use-debounce";
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { useI18n } from "@/lib/i18n";
import type { CreateShortcutInput } from "@/lib/utils";

const CreateShortcutForm = ({
	formData,
	onFormDataChange,
	hasOptional = true,
}: {
	formData: CreateShortcutInput;
	onFormDataChange: (data: CreateShortcutInput) => void;
	hasOptional?: boolean;
}) => {
	const { t } = useI18n();
	const debouncedUpdate = useDebouncedCallback((data: CreateShortcutInput) => {
		onFormDataChange(data);
	}, 80);

	const handleChange = (key: keyof CreateShortcutInput, value: string) => {
		debouncedUpdate({
			...formData,
			[key]: value,
		});
	};

	return (
		<>
			<Field>
				<FieldLabel htmlFor="url">{t("shortcut.url")}</FieldLabel>
				<Input
					id="url"
					name="url"
					autoComplete="off"
					required
					placeholder="https://example.com"
					type="url"
					value={formData.url}
					onChange={(e) => {
						onFormDataChange({ ...formData, url: e.target.value });
					}}
				/>
			</Field>
			<Field>
				<FieldLabel htmlFor="name">
					{t("shortcut.name")} {hasOptional && `(${t("common.optional")})`}
				</FieldLabel>
				<Input
					id="name"
					name="name"
					autoComplete="off"
					placeholder="Example.com"
					value={formData.name}
					onChange={(e) => {
						onFormDataChange({ ...formData, name: e.target.value });
					}}
				/>
				{hasOptional && (
					<FieldDescription>{t("shortcut.nameDescription")}</FieldDescription>
				)}
			</Field>
			<Field>
				<FieldLabel htmlFor="accentColor">
					{t("shortcut.bgColor")} {hasOptional && `(${t("common.optional")})`}
				</FieldLabel>
				<Input
					id="accentColor"
					type="color"
					value={formData.accentColor ?? "#000000"}
					onChange={(e) => {
						handleChange("accentColor", e.target.value);
					}}
				/>
				{hasOptional && (
					<FieldDescription>{t("shortcut.colorDescription")}</FieldDescription>
				)}
			</Field>

			<Field>
				<FieldLabel htmlFor="mutedColor">
					{t("shortcut.mutedColor")}{" "}
					{hasOptional && `(${t("common.optional")})`}
				</FieldLabel>
				<Input
					id="mutedColor"
					type="color"
					value={formData.mutedColor ?? "#000000"}
					onChange={(e) => {
						handleChange("mutedColor", e.target.value);
					}}
				/>
				{hasOptional && (
					<FieldDescription>{t("shortcut.colorDescription")}</FieldDescription>
				)}
			</Field>
		</>
	);
};

export default CreateShortcutForm;
