// src/components/ShortcutGroupDialogDrop.vue
<script setup lang="ts">
import { useDroppable } from "@dnd-kit/vue";
import { Teleport, useTemplateRef } from "vue";

const droppableRef = useTemplateRef("droppableRef");

const { isDropTarget } = useDroppable({
  id: "dialogDrop",
  type: "group-dialog-drop",
  collisionPriority: 1,
  element: droppableRef,
});
</script>

<template>
  <Teleport to="body">
    <div
      ref="droppableRef"
      :class="[
        'fixed inset-0 z-20 transition-colors',
        { 'bg-accent/60': isDropTarget },
      ]"
    ></div>
  </Teleport>
</template>

// src/newtab/components/shortcut-group-dialog-drop.tsx
import { useDroppable } from "@dnd-kit/react";
import { createPortal } from "react-dom";

const ShortcutGroupDialogDrop = () => {
	const { ref, isDropTarget } = useDroppable({
		id: "dialogDrop",
		type: "group-dialog-drop",
		collisionPriority: 1,
	});

	return createPortal(
		<div
			ref={ref}
			className={`fixed inset-0 z-20 transition-colors ${isDropTarget ? "bg-accent/20" : ""}`}
		></div>,
		document.body,
	);
};

export default ShortcutGroupDialogDrop;
