// src/newtab/components/delete-shortcut-button.tsx
import { TrashIcon } from "lucide-react";
import { type ComponentProps, memo } from "react";
import { useStorage } from "@/components/providers/storage-provider";
import { Button } from "@/components/ui/button";
import { deleteIcon } from "@/lib/storage";
import type { ShortcutGroupType, ShortcutType } from "@/lib/types";

const DeleteShortcutButton = ({
	shortcut,
	onClick,
	...props
}: { shortcut: ShortcutType } & OmitTyped<
	ComponentProps<typeof Button>,
	"children"
>) => {
	const { storage, setShortcuts } = useStorage();

	return (
		<Button
			{...props}
			onClick={async (e) => {
				onClick?.(e);

				if (shortcut.groupId) {
					const shortcutGroup = storage.shortcuts.find(
						(p): p is ShortcutGroupType =>
							p.type === "group" && p.id === shortcut.groupId,
					);

					if (shortcutGroup) {
						const shortcutGroupItems = shortcutGroup.items.filter(
							(p) => p.id !== shortcut.id,
						);

						if (shortcutGroupItems.length === 0) {
							setShortcuts(
								storage.shortcuts.filter((p) => p.id !== shortcut.groupId),
							);

							return;
						}

						setShortcuts(
							storage.shortcuts.map((s) => {
								if (s.id === shortcutGroup.id) {
									return { ...s, items: shortcutGroupItems };
								}

								return s;
							}),
						);
					}
				} else {
					setShortcuts(storage.shortcuts.filter((p) => p.id !== shortcut.id));
				}

				await deleteIcon(shortcut.id);
			}}
		>
			<TrashIcon />
		</Button>
	);
};

export default memo(DeleteShortcutButton);

// src/components/DeleteShortcutButton.vue
<script setup lang="ts">
import Button from "@/components/ui/button/Button.vue";
import { deleteIcon, storage } from "@/lib/storage";
import { ShortcutGroupType, ShortcutType } from "@/lib/types";
import { TrashIcon } from "@lucide/vue";

const props = defineProps<{
  shortcut: ShortcutType;
}>();
</script>

<template>
  <Button
    @click="
      async () => {
        if (shortcut.groupId) {
          const shortcutGroup = storage.shortcuts.find(
            (p): p is ShortcutGroupType =>
              p.type === 'group' && p.id === shortcut.groupId,
          );

          if (shortcutGroup) {
            const shortcutGroupItems = shortcutGroup.items.filter(
              (p) => p.id !== shortcut.id,
            );

            if (shortcutGroupItems.length === 0) {
              storage.shortcuts = storage.shortcuts.filter(
                (p) => p.id !== shortcut.groupId,
              );

              return;
            }

            storage.shortcuts = storage.shortcuts.map((s) => {
              if (s.id === shortcutGroup.id) {
                return { ...s, items: shortcutGroupItems };
              }

              return s;
            });
          }
        } else {
          storage.shortcuts = storage.shortcuts.filter(
            (p) => p.id !== shortcut.id,
          );
        }

        await deleteIcon(shortcut.id);
      }
    "
  >
    <TrashIcon />
  </Button>
</template>
