// src/newtab/components/preview-shortcut-item.tsx
import {
	type ComponentProps,
	type CSSProperties,
	useCallback,
	useEffect,
	useState,
} from "react";
import { getIconByName } from "@/lib/storage";
import type { ShortcutType } from "@/lib/types";
import { cn } from "@/lib/utils";

const PreviewShortcutItem = ({
	shortcut,
	className,
	style,
	...props
}: { shortcut: ShortcutType } & ComponentProps<"div">) => {
	const [iconBlob, setIconBlob] = useState<Blob | undefined>(undefined);
	const [iconBlobUrl, setIconBlobUrl] = useState<string | undefined>(undefined);

	const loadIcon = useCallback(async () => {
		const icon = await getIconByName(shortcut.id);
		if (icon) setIconBlob(icon.blob);
	}, [shortcut.id]);

	useEffect(() => {
		loadIcon();
	}, [loadIcon]);

	useEffect(() => {
		let _iconBlobUrl = "";
		if (iconBlob) {
			_iconBlobUrl = URL.createObjectURL(iconBlob);
			setIconBlobUrl(_iconBlobUrl);
		}
		return () => {
			if (_iconBlobUrl !== "") URL.revokeObjectURL(_iconBlobUrl);
		};
	}, [iconBlob]);

	return (
		<div
			className={cn([
				className,
				"flex flex-col items-center justify-center gap-1 bg-(--color) p-2 rounded-lg min-h-0 overflow-hidden",
			])}
			style={
				{
					"--color": shortcut.accentColor,
					"--muted-color": shortcut.mutedColor,
				} as CSSProperties
			}
			{...props}
		>
			<img
				src={iconBlobUrl}
				alt={shortcut.name}
				className="min-h-0 flex-1 w-auto max-w-full object-contain"
			/>
		</div>
	);
};

export default PreviewShortcutItem;

// src/components/PreviewShortcutItem.vue
<script setup lang="ts">
import { getIconById } from "@/lib/storage";
import { ShortcutType } from "@/lib/types";
import { cn } from "@/lib/utils";
import { computed, ref, watch } from "vue";

const props = defineProps<{
  class?: string;
  shortcut: ShortcutType;
}>();

const iconBlob = ref<Blob | undefined>(undefined);

const iconBlobUrl = computed<string | undefined>((oldValue) => {
  if (oldValue) URL.revokeObjectURL(oldValue);

  if (iconBlob.value) {
    return URL.createObjectURL(iconBlob.value);
  }

  return undefined;
});

watch(
  () => props.shortcut,
  async (newShortcut) => {
    if (!newShortcut?.id) return;
    const icon = await getIconById(newShortcut.id);
    if (icon) iconBlob.value = icon.blob;
  },
  { immediate: true },
);
</script>

<template>
  <div
    :class="
      cn([
        props.class,
        'flex flex-col items-center justify-center gap-1 bg-(--color) p-2 rounded-lg min-h-0 overflow-hidden',
      ])
    "
    :style="{
      '--color': shortcut.accentColor,
      '--muted-color': shortcut.mutedColor,
    }"
  >
    <img
      :src="iconBlobUrl"
      :alt="shortcut.name"
      class="min-h-0 flex-1 w-auto max-w-full object-contain"
    />
  </div>
</template>
