// src/newtab/components/search-bar.tsx
import { ChevronRightIcon, SearchIcon } from "lucide-react";
import { useId, useRef, useState } from "react";
import { useDebouncedCallback } from "use-debounce";
import { InputGroup, InputGroupAddon } from "@/components/ui/input-group";
import { Skeleton } from "@/components/ui/skeleton";
import { useChromeSearch } from "@/lib/hooks/use-chrome-search";
import { useI18n } from "@/lib/i18n";
import { cn } from "@/lib/utils";

type DuckDuckGoSuggestions = [string, string[]];

const SearchBar = ({ className }: { className?: string }) => {
  const { search } = useChromeSearch();
  const { t } = useI18n();
  const listId = useId();
  const latestRequestRef = useRef(0);
  const typedQueryRef = useRef("");
  const [searchQuery, setSearchQuery] = useState("");
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [activeSuggestionIndex, setActiveSuggestionIndex] = useState(-1);
  const [isSuggestionsOpen, setIsSuggestionsOpen] = useState(false);
  const [isFetching, setIsFetching] = useState(false);

  const loadSuggestions = useDebouncedCallback(async (searchValue: string) => {
    const normalizedSearchValue = searchValue.trim();

    if (!normalizedSearchValue) {
      setSuggestions([]);
      setIsFetching(false);
      return;
    }

    const requestId = latestRequestRef.current + 1;
    latestRequestRef.current = requestId;
    setIsFetching(true);

    try {
      const res = await fetch(
        `https://duckduckgo.com/ac/?q=${encodeURIComponent(normalizedSearchValue)}&type=list`,
      );
      const data = (await res.json()) as DuckDuckGoSuggestions;

      if (requestId !== latestRequestRef.current) return;

      setSuggestions(data[1]);
      setIsSuggestionsOpen(true);
    } catch {
      if (requestId !== latestRequestRef.current) return;
      setSuggestions([]);
    } finally {
      if (requestId === latestRequestRef.current) {
        setIsFetching(false);
      }
    }
  }, 250);

  const searchCurrentQuery = () => {
    const query = searchQuery.trim();

    if (!query) return;

    setIsSuggestionsOpen(false);
    setActiveSuggestionIndex(-1);
    search(query);
  };

  const updateQuery = (query: string) => {
    typedQueryRef.current = query;
    setSearchQuery(query);
    setActiveSuggestionIndex(-1);

    if (!query.trim()) {
      loadSuggestions.cancel();
      setSuggestions([]);
      setIsFetching(false);
      setIsSuggestionsOpen(false);
      return;
    }

    setIsSuggestionsOpen(true);
    loadSuggestions(query);
  };

  const selectSuggestionPreview = (nextIndex: number) => {
    setActiveSuggestionIndex(nextIndex);
    setSearchQuery(
      nextIndex === -1 ? typedQueryRef.current : suggestions[nextIndex],
    );
  };

  const hasSuggestions = suggestions.length > 0;
  const shouldShowSuggestions =
    isSuggestionsOpen &&
    (Boolean(searchQuery.trim()) || loadSuggestions.isPending() || isFetching);

  return (
    <div className={cn(["relative w-full", className])}>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          searchCurrentQuery();
        }}
      >
        <SearchInput
          aria-activedescendant={
            activeSuggestionIndex >= 0
              ? `${listId}-${activeSuggestionIndex}`
              : undefined
          }
          aria-autocomplete="list"
          aria-controls={listId}
          aria-expanded={shouldShowSuggestions}
          autoComplete="off"
          onBlur={() => {
            window.setTimeout(() => setIsSuggestionsOpen(false), 100);
          }}
          onChange={(e) => updateQuery(e.target.value)}
          onFocus={() => {
            if (searchQuery.trim()) setIsSuggestionsOpen(true);
          }}
          onKeyDown={(e) => {
            if (e.key === "ArrowDown" && hasSuggestions) {
              e.preventDefault();
              const nextIndex =
                activeSuggestionIndex >= suggestions.length - 1
                  ? -1
                  : activeSuggestionIndex + 1;
              selectSuggestionPreview(nextIndex);
            }

            if (e.key === "ArrowUp" && hasSuggestions) {
              e.preventDefault();
              const nextIndex =
                activeSuggestionIndex <= -1
                  ? suggestions.length - 1
                  : activeSuggestionIndex - 1;
              selectSuggestionPreview(nextIndex);
            }

            if (e.key === "Escape") {
              setSearchQuery(typedQueryRef.current);
              setActiveSuggestionIndex(-1);
              setIsSuggestionsOpen(false);
            }
          }}
          placeholder={t("search.placeholder")}
          role="combobox"
          spellCheck="false"
          value={searchQuery}
        />
        {shouldShowSuggestions && (
          <div className="absolute top-full z-40 mt-1 w-full animate-in fade-in-0 zoom-in-95 px-4">
            <div
              className={cn(
                "overflow-hidden rounded-lg border border-white/10 bg-white/5 shadow-lg backdrop-blur-xl",
                !hasSuggestions &&
                  !(loadSuggestions.isPending() || isFetching) &&
                  "border-transparent bg-transparent shadow-none backdrop-blur-none",
              )}
            >
              {(loadSuggestions.isPending() || isFetching) && (
                <div className="grid grid-cols-1 gap-1 p-1">
                  {Array(6)
                    .fill(null)
                    .map((_, idx) => (
                      <Skeleton
                        className="h-9 w-full rounded-sm px-2 py-1.5"
                        key={idx}
                      />
                    ))}
                </div>
              )}
              {!(loadSuggestions.isPending() || isFetching) &&
                hasSuggestions && (
                  <div
                    id={listId}
                    role="listbox"
                    className="grid grid-cols-1 p-1"
                  >
                    {suggestions.map((suggestion, index) => (
                      <button
                        aria-selected={activeSuggestionIndex === index}
                        className={cn(
                          "flex h-9 cursor-pointer items-center rounded-sm px-2 text-left text-sm text-white transition-colors",
                          activeSuggestionIndex === index
                            ? "bg-white/15"
                            : "hover:bg-white/10",
                        )}
                        id={`${listId}-${index}`}
                        key={`${suggestion}-${index}`}
                        onMouseDown={(e) => e.preventDefault()}
                        onMouseEnter={() => setActiveSuggestionIndex(index)}
                        onClick={() => {
                          setSearchQuery(suggestion);
                          setIsSuggestionsOpen(false);
                          search(suggestion);
                        }}
                        role="option"
                        tabIndex={-1}
                        type="button"
                      >
                        {suggestion}
                      </button>
                    ))}
                  </div>
                )}
            </div>
          </div>
        )}
      </form>
    </div>
  );
};

export default SearchBar;

const SearchInput = ({
  className,
  ...props
}: React.ComponentProps<"input">) => {
  return (
    <div data-slot="command-input-wrapper" className="p-1 pb-0">
      <InputGroup className="h-14 w-full rounded-full border border-white/10 bg-white/5 p-2 text-base text-white outline-none transition duration-200 focus:border-white/20 focus:bg-white/10 *:data-[slot=input-group-addon]:pl-2!">
        <InputGroupAddon align="inline-start">
          <SearchIcon className="pointer-events-none size-5 text-muted-foreground" />
        </InputGroupAddon>
        <input
          data-slot="command-input"
          className={cn(
            "ml-2 w-full bg-transparent text-sm outline-hidden",
            className,
          )}
          {...props}
        />
        <InputGroupAddon align="inline-end">
          <button
            type="submit"
            className="size-9 place-items-center rounded-full border border-primary/30 bg-primary/15 text-primary transition-colors hover:bg-primary/20"
          >
            <ChevronRightIcon className="translate-x-px" />
          </button>
        </InputGroupAddon>
      </InputGroup>
    </div>
  );
};

// src/components/SearchBar.vue
<script setup lang="ts">
import SearchInput from "@/components/SearchInput.vue";
import Skeleton from "@/components/ui/skeleton/Skeleton.vue";
import { t} from "@/lib/i18n";
import { getSearchUrl } from "@/lib/search-engines";
import { storage } from "@/lib/storage";
import { cn } from "@/lib/utils";
import { useDebounceFn } from "@vueuse/core";
import { computed, ref, useId } from "vue";

type DuckDuckGoSuggestions = [string, string[]];

const props = defineProps<{
  class: string;
}>();

const search = (query: string) => {
  if (!query.trim()) return;
  if (typeof chrome !== "undefined" && chrome.search?.query)
    chrome.search.query({ text: query, disposition: "CURRENT_TAB" });
  else
    window.location.href = `https://www.google.com/search?q=${encodeURIComponent(query)}`;
};

const searchInIncognito = async (query: string) => {
  const trimmedQuery = query.trim();
  if (!trimmedQuery) return;

  if (typeof chrome !== "undefined" && chrome.search?.query && chrome.windows) {
    const allowed = await chrome.extension.isAllowedIncognitoAccess();
    if (!allowed) {
      alert(t("search.allowIncognito"));
      return;
    }

    try {
      const incognitoWindow = await chrome.windows.create({
        incognito: true,
        focused: true,
        state: "maximized",
        setSelfAsOpener: true,
      });

      const incognitoTabId = incognitoWindow?.tabs?.[0]?.id;

      if (!incognitoTabId) throw new Error();

      chrome.search.query({
        text: trimmedQuery,
        tabId: incognitoTabId,
      });
      window.close();
    } catch (error) {
      window.open(
        `https://www.google.com/search?q=${encodeURIComponent(trimmedQuery)}`,
        "_blank",
      );
    }
  } else {
    window.location.href = `https://www.google.com/search?q=${encodeURIComponent(trimmedQuery)}`;
  }
};


const listId = useId();
const latestRequestRef = ref(0);
const typedQuery = ref("");
const searchQuery = ref("");
const suggestions = ref<string[]>([]);
const activeSuggestionIndex = ref(-1);
const isSuggestionsOpen = ref(false);
const isFetching = ref(false);

const hasSuggestions = computed(() => suggestions.value.length > 0);

const shouldShowSuggestions = computed(() => {
  return (
    isSuggestionsOpen.value &&
    (Boolean(searchQuery.value.trim()) ||
      loadSuggestions.isPending.value ||
      isFetching.value)
  );
});

const loadSuggestions = useDebounceFn(async (searchValue: string) => {
  const normalizedSearchValue = searchValue.trim();

  if (!normalizedSearchValue) {
    suggestions.value = [];
    isFetching.value = false;
    return;
  }

  const requestId = latestRequestRef.value + 1;
  latestRequestRef.value = requestId;
  isFetching.value = true;

  try {
    const res = await fetch(
      `https://duckduckgo.com/ac/?q=${encodeURIComponent(normalizedSearchValue)}&type=list`,
    );
    const data = (await res.json()) as DuckDuckGoSuggestions;

    if (requestId !== latestRequestRef.value) return;

    suggestions.value = data[1];
    isSuggestionsOpen.value = true;
  } catch {
    if (requestId !== latestRequestRef.value) return;
    suggestions.value = [];
  } finally {
    if (requestId === latestRequestRef.value) {
      isFetching.value = false;
    }
  }
}, 400);

const searchCurrentQuery = () => {
  const query = searchQuery.value.trim();

  if (!query) return;

  isSuggestionsOpen.value = false;
  activeSuggestionIndex.value = -1;

  if (storage.settings.searchEngine === "default") search(query);
  else
    window.location.href = getSearchUrl(storage.settings.searchEngine, query);
};

const searchCurrentQueryInIncognito = () => {
  const query = searchQuery.value.trim();

  if (!query) return;

  isSuggestionsOpen.value = false;
  activeSuggestionIndex.value = -1;

  if (storage.settings.searchEngine === "default") searchInIncognito(query);
  else {
    chrome.windows.create({
      url: getSearchUrl(storage.settings.searchEngine, query),
      incognito: true,
      state: "maximized",
    });
    window.close();
  }
};

const updateQuery = async (query: string) => {
  typedQuery.value = query;
  searchQuery.value = query;

  activeSuggestionIndex.value = -1;

  if (!query.trim()) {
    loadSuggestions.cancel();
    suggestions.value = [];
    isFetching.value = false;
    isSuggestionsOpen.value = false;
    return;
  }

  isSuggestionsOpen.value = true;
  await loadSuggestions(query);
};

const selectSuggestionPreview = (nextIndex: number) => {
  activeSuggestionIndex.value = nextIndex;
  searchQuery.value =
    nextIndex === -1 ? typedQuery.value : suggestions.value[nextIndex];
};

const handleBlur = () => {
  setTimeout(() => (isSuggestionsOpen.value = false), 100);
};
</script>

<template>
  <div :class="cn(['relative w-full', props.class])">
    <form
      @submit="
        (e) => {
          e.preventDefault();
          searchCurrentQuery();
        }
      "
    >
      <SearchInput
        :aria-activedescendant="
          activeSuggestionIndex >= 0
            ? `${listId}-${activeSuggestionIndex}`
            : undefined
        "
        aria-autocomplete="list"
        :aria-controls="listId"
        :aria-expanded="shouldShowSuggestions"
        autocomplete="off"
        @blur="handleBlur"
        @input="
          (e: InputEvent) => {
            const target = e.target as HTMLInputElement;
            updateQuery(target.value);
          }
        "
        @incognito-request="searchCurrentQueryInIncognito"
        @focus="() => (searchQuery.trim() ? (isSuggestionsOpen = true) : '')"
        @keydown="
          (e: KeyboardEvent) => {
            if (e.key === 'ArrowDown' && hasSuggestions) {
              e.preventDefault();
              e.stopPropagation();
              isSuggestionsOpen = true;
              const nextIndex =
                activeSuggestionIndex >= suggestions.length - 1
                  ? -1
                  : activeSuggestionIndex + 1;
              selectSuggestionPreview(nextIndex);
            }

            if (e.key === 'ArrowUp' && hasSuggestions) {
              e.preventDefault();
              e.stopPropagation();
              isSuggestionsOpen = true;
              const nextIndex =
                activeSuggestionIndex <= -1
                  ? suggestions.length - 1
                  : activeSuggestionIndex - 1;
              selectSuggestionPreview(nextIndex);
            }

            if (e.key === 'Escape') {
              searchQuery = typedQuery;
              activeSuggestionIndex = -1;
              isSuggestionsOpen = false;
            }

            if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
              e.preventDefault();
              e.stopPropagation();
              searchCurrentQueryInIncognito();
            }
          }
        "
        :placeholder="t('search.placeholder')"
        role="combobox"
        spellCheck="false"
        :value="searchQuery"
        id="searchInput"
      />
      <div
        v-if="shouldShowSuggestions"
        class="absolute top-full z-40 mt-1 w-full animate-in fade-in-0 zoom-in-95 px-4"
      >
        <div
          :class="
            cn(
              'overflow-hidden rounded-lg border border-white/10 bg-white/5 shadow-lg backdrop-blur-xl',
              !hasSuggestions &&
                !(loadSuggestions.isPending.value || isFetching) &&
                'border-transparent bg-transparent shadow-none backdrop-blur-none',
            )
          "
        >
          <div
            v-if="loadSuggestions.isPending.value || isFetching"
            class="grid grid-cols-1 gap-1 p-1"
          >
            <Skeleton
              v-for="(_, idx) in Array(6).fill(null)"
              class="h-9 w-full rounded-sm px-2 py-1.5"
              :key="idx"
            />
          </div>
          <div
            v-else-if="
              !(loadSuggestions.isPending.value || isFetching) && hasSuggestions
            "
            :id="listId"
            role="listbox"
            class="grid grid-cols-1 p-1"
          >
            <button
              v-for="(suggestion, index) in suggestions"
              :aria-selected="activeSuggestionIndex === index"
              :class="
                cn(
                  'flex h-9 cursor-pointer items-center rounded-sm px-2 text-left text-sm text-white transition-colors',
                  activeSuggestionIndex === index
                    ? 'bg-white/15'
                    : 'hover:bg-white/10',
                )
              "
              :id="`${listId}-${index}`"
              :key="`${suggestion}-${index}`"
              @mousedown="(e) => e.preventDefault()"
              @mouseenter="() => (activeSuggestionIndex = index)"
              @click="
                () => {
                  searchQuery = suggestion;
                  isSuggestionsOpen = false;
                  search(suggestion);
                }
              "
              role="option"
              tabindex="-1"
              type="button"
            >
              {{ suggestion }}
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
</template>
