// src/newtab/components/shortcut-item.tsx
﻿import { pointerIntersection } from "@dnd-kit/collision";
import { useDroppable } from "@dnd-kit/react";
import { useSortable } from "@dnd-kit/react/sortable";
import { Edit2Icon, FolderPlusIcon } from "lucide-react";
import { type ComponentProps, useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { useI18n } from "@/lib/i18n";
import { getIconByName } from "@/lib/storage";
import type { ShortcutType } from "@/lib/types";
import { cn } from "@/lib/utils";
import DeleteShortcutButton from "@/newtab/components/delete-shortcut-button";
import EditShortcutDialog from "@/newtab/components/edit-shortcut-dialog";

export const GROUP_DROP_PREFIX = "shortcut-drop:";

export type ShortcutItemCSSVars = React.CSSProperties & {
	"--color"?: string;
};

export const shortcutItemClassName =
	"flex flex-col items-center justify-center rounded-lg relative aspect-video";

const ShortcutItem = ({
	className,
	shortcut,
	index,
	inGroup = false,
	...props
}: {
	shortcut: ShortcutType;
	index: number;
	inGroup?: boolean;
} & ComponentProps<"div">) => {
	const { t } = useI18n();
	const [iconBlob, setIconBlob] = useState<Blob | undefined>(undefined);
	const [iconBlobUrl, setIconBlobUrl] = useState<string | undefined>(undefined);

	const {
		ref: sortableRef,
		handleRef,
		sortable,
	} = useSortable({
		id: shortcut.id,
		index,
		collisionDetector: pointerIntersection,
		type: "shortcut",
		group: "main-shortcuts",
	});

	const manager = sortable.manager;

	const sourceId = manager?.dragOperation.source?.id;
	const sourceType = manager?.dragOperation.source?.type?.toString();

	const { ref: dropRef, isDropTarget } = useDroppable({
		id: `${GROUP_DROP_PREFIX}${shortcut.id}`,
		data: { targetId: shortcut.id },
		disabled: inGroup,
	});

	const isGroupTarget =
		isDropTarget && sourceId !== shortcut.id && sourceType === "shortcut";

	const loadIcon = useCallback(async () => {
		const icon = await getIconByName(shortcut.id);

		if (icon) setIconBlob(icon.blob);
	}, [shortcut.id]);

	useEffect(() => {
		loadIcon();
	}, [loadIcon]);

	useEffect(() => {
		let _iconBlobUrl = "";
		if (iconBlob) {
			_iconBlobUrl = URL.createObjectURL(iconBlob);
			setIconBlobUrl(_iconBlobUrl);
		}
		return () => {
			if (_iconBlobUrl !== "") URL.revokeObjectURL(_iconBlobUrl);
		};
	}, [iconBlob]);

	return (
		<div
			className="relative group"
			{...props}
			ref={(e) => {
				sortableRef(e);
			}}
		>
			<a
				ref={handleRef}
				href={shortcut.url}
				rel="noreferrer"
				className={cn(className, shortcutItemClassName, 'h-full')}
				style={{ background: shortcut.accentColor }}
			>
				{iconBlobUrl && (
					<img src={iconBlobUrl} alt={shortcut.name} className="size-12 mb-2" />
				)}
				<span className={`${iconBlobUrl ? 'text-lg' : 'text-xl'}`} style={{ color: shortcut.mutedColor }}>
					{shortcut.name}
				</span>

				<div ref={dropRef} className="absolute inset-[25%] rounded-md z-0" />

				{isGroupTarget && (
					<div className="absolute flex flex-col items-center justify-center inset-0 rounded-lg bg-black/50 ...">
						<FolderPlusIcon className="size-8 text-white" />
						<span className="text-xl">{t("shortcut.createGroup")}</span>
					</div>
				)}
			</a>

			<EditShortcutDialog
				shortcut={shortcut}
				onIconChange={async () => {
					await loadIcon();
				}}
				render={
					<Button
						variant="ghost"
						size="icon"
						className="absolute top-1 right-1 text-transparent group-hover:text-(--color) transition-colors duration-300 z-10"
						style={{ "--color": shortcut.mutedColor } as ShortcutItemCSSVars}
					>
						<Edit2Icon />
					</Button>
				}
			/>
			<DeleteShortcutButton
				shortcut={shortcut}
				variant="ghost"
				size="icon"
				className="absolute bottom-1 right-1 text-transparent group-hover:text-(--color) transition-colors duration-300 z-10"
				style={{ "--color": shortcut.mutedColor } as ShortcutItemCSSVars}
			/>
		</div>
	);
};

export default ShortcutItem;

// src/components/ShortcutItem.vue
<script setup lang="ts">
import DeleteShortcutButton from "@/components/DeleteShortcutButton.vue";
import EditShortcutDialog from "@/components/EditShortcutDialog.vue";
import Button from "@/components/ui/button/Button.vue";
import { GROUP_DROP_PREFIX, shortcutItemClassName } from "@/lib/constants";
import { t } from "@/lib/i18n";
import { getIconById } from "@/lib/storage";
import { ShortcutType } from "@/lib/types";
import { cn } from "@/lib/utils";
import { pointerIntersection } from "@dnd-kit/collision";
import { useDroppable } from "@dnd-kit/vue";
import { useSortable } from "@dnd-kit/vue/sortable";
import { Edit2Icon, GroupIcon } from "@lucide/vue";
import { computed, onUnmounted, ref, useTemplateRef, watch } from "vue";

const props = withDefaults(
  defineProps<{
    class?: string;
    shortcut: ShortcutType;
    index: number;
    inGroup?: boolean;
  }>(),
  {
    inGroup: false,
  },
);

const sortableRef = useTemplateRef("sortableRef");
const handleRef = useTemplateRef("handleRef");
const dropRef = useTemplateRef("dropRef");

const iconBlob = ref<Blob>();
const iconBlobUrl = ref<string>();

watch(
  () => props.shortcut,
  async (newShortcut) => {
    if (!newShortcut?.id) return;

    const icon = await getIconById(newShortcut.id);

    if (!icon) {
      iconBlob.value = undefined;
      return;
    }

    iconBlob.value = icon.blob;
  },
  { immediate: true },
);

watch(iconBlob, (blob) => {
  if (iconBlobUrl.value) {
    URL.revokeObjectURL(iconBlobUrl.value);
    iconBlobUrl.value = undefined;
  }

  if (blob) {
    iconBlobUrl.value = URL.createObjectURL(blob);
  }
});

watch(
  () => props.shortcut,
  async (newShortcut) => {
    if (!newShortcut?.id) return;
    const icon = await getIconById(newShortcut.id);
    if (icon) iconBlob.value = icon.blob;
  },
  { immediate: true },
);

onUnmounted(() => {
  if (iconBlobUrl.value) URL.revokeObjectURL(iconBlobUrl.value);
});

// DnD logic
const { sortable } = useSortable({
  id: props.shortcut.id,
  index: props.index,
  type: "shortcut",
  group: "main-shortcuts",
  element: sortableRef,
  handle: handleRef,
  collisionDetector: () => pointerIntersection,
});

const isGroupTarget = computed(() => {
  const manager = sortable.value?.manager;
  if (!manager?.dragOperation) return false;

  const sourceId = manager.dragOperation.source?.id;
  const sourceType = manager.dragOperation.source?.type?.toString();
  return (
    isDropTarget.value &&
    sourceId !== props.shortcut.id &&
    sourceType === "shortcut"
  );
});

const { isDropTarget } = useDroppable({
  id: `${GROUP_DROP_PREFIX}${props.shortcut.id}`,
  data: { targetId: props.shortcut.id },
  disabled: props.inGroup,
  element: dropRef,
});
</script>

<template>
  <div class="relative group" ref="sortableRef">
    <a
      ref="handleRef"
      :href="shortcut.url"
      :class="cn(props.class, shortcutItemClassName, 'h-full')"
      :style="{ background: shortcut.accentColor }"
      rel="noreferrer"
    >
      <img
        v-if="iconBlobUrl"
        :src="iconBlobUrl"
        :alt="shortcut.name"
        class="size-12 mb-2"
      />
      <span
        :class="`${iconBlobUrl ? 'text-lg' : 'text-xl'}`"
        :style="{ color: shortcut.mutedColor }"
      >
        {{ shortcut.name }}
      </span>

      <div ref="dropRef" class="absolute inset-[25%] rounded-md z-0"></div>

      <div
        v-if="isGroupTarget"
        class="absolute flex flex-col items-center justify-center inset-0 rounded-lg bg-black/50 z-20"
      >
        <GroupIcon />
        <span class="text-xl">{{ t("shortcut.createGroup") }}</span>
      </div>
    </a>

    <EditShortcutDialog
      :shortcut="shortcut"
      @icon-change="
        async () => {
          const icon = await getIconById(shortcut.id);

          if (!icon) {
            iconBlob = undefined;
            return;
          }

          iconBlob = icon.blob;
        }
      "
      as-child
    >
      <Button
        variant="ghost"
        size="icon"
        class="absolute top-1 right-1 text-transparent group-hover:text-(--color) transition-colors duration-300 z-10"
        :style="{ '--color': shortcut.mutedColor }"
      >
        <Edit2Icon />
      </Button>
    </EditShortcutDialog>

    <DeleteShortcutButton
      :shortcut="shortcut"
      variant="ghost"
      size="icon"
      class="absolute bottom-1 right-1 text-transparent group-hover:text-(--color) transition-colors duration-300 z-10"
      :style="{ '--color': shortcut.mutedColor }"
    />
  </div>
</template>
